### PR TITLE
rich presence function

### PR DESCRIPTION
**Pull request by TheBunnyMan123**
@PoolloverNathan please add a config option for application ID

### CODE REVIEW

**Comment by TheBunnyMan123** [comment]
this builds on my machine, why not here

**Review by FokoHetman — APPROVED** [review]
cool

**Comment by PoolloverNathan** [comment]
huh did CI actually accept the challengt

**Comment by TheBunnyMan123** [comment]
Closing this because this will be in limbo forever because of a stupid issue we can't figure out that only affects GitHub actions

**Pull request closed without merging**
