### PR TITLE
Add installation script to flake

### PR DESCRIPTION
**Pull request by PoolloverNathan**
Adds the `install` app to the flake, which copies the latest output jar into a Prism Launcher instance using Bash black-magic fuckery. Also adds `build-install`, which automatically builds the mod in a temporary directory (ideal for e.g. `nix run github:Figura-Goofballs/GoofyPlugin#build-install`).

### CODE REVIEW

**Comment by TheBunnyMan123** [comment]
It should also have the mod menu mod installed to make sure the mod is actually loading

**Comment by PoolloverNathan** [comment]
> It should also have the mod menu mod installed to make sure the mod is actually loading

@TheBunnyMan123 instance users decide whether or not they want modmenu

**Comment by PoolloverNathan** [comment]
actually I should assert it's a fabric instance

**Comment by PoolloverNathan** [comment]
don't merge yet

**Review by TheBunnyMan123 — APPROVED** [review]
I'm sure this works, you're the nix guy after all

**Pull request merged**
