### PR TITLE
Mod menu stuff

### PR DESCRIPTION
**Pull request by TheBunnyMan123**

### CODE REVIEW

**Review by PoolloverNathan — CHANGES_REQUESTED** [review]
edit description in gradle.properties

**Comment by TheBunnyMan123** [comment]
> edit description in gradle.properties

I tried that it doesn't work

**Comment by TheBunnyMan123** [comment]
it says something fucking weird

**Comment by TheBunnyMan123** [comment]
> edit description in gradle.properties

@PoolloverNathan it says "Processes main resources." when doing it like that

**Review by PoolloverNathan — APPROVED** [review]
five figurabucks says it works

**Pull request merged**
