### PR TITLE
Relicense to APACHE 2.0

### PR DESCRIPTION
**Pull request by TheBunnyMan123**

### CODE REVIEW

**Review by FokoHetman — APPROVED** [review]
fair enough

**Review by PoolloverNathan — CHANGES_REQUESTED** [review]
rejecting to block merge until approvals:
- [x] @PoolloverNathan 
- [ ] @4P5 
- [ ] @UnlikePaladin
- [x] @FokoHetman

**Review by UnlikePaladin — APPROVED** [review]
Lgtm

**Review by 4P5 — APPROVED** [review]
lgtm

**Pull request merged**
