### PR TITLE
fix: just return components

### PR DESCRIPTION
**Pull request by PoolloverNathan**
yeah so apparently you can just… return them, and figura will handle serializing them for you. fixes 1.21.

### CODE REVIEW

**Comment by TheBunnyMan123** [comment]
You're not gonna believe this: String[] can't contain components

**Comment by TheBunnyMan123** [comment]
Screenshot_20241217-113704

**Comment by PoolloverNathan** [comment]
i thought I fixed this

**Comment by TheBunnyMan123** [comment]
Why draft

**Comment by PoolloverNathan** [comment]
> Why draft

untested; does it work?

**Comment by TheBunnyMan123** [comment]
idfk I'ma test it later

**Comment by PoolloverNathan** [comment]
works on my machine

**Review by TheBunnyMan123 — APPROVED** [review]
yeah it works

**Comment by PoolloverNathan** [comment]
works on my machine

**Comment by PoolloverNathan** [comment]
oops hit the wrong command from history

**Pull request merged**
