### PR TITLE
Fix lack of brain while setting up flake

### PR DESCRIPTION
**Pull request by PoolloverNathan**

### CODE REVIEW

**Review by TheBunnyMan123 — APPROVED** [review]
E

**Comment by PoolloverNathan** [comment]
forgot flakes

**Comment by PoolloverNathan** [comment]
checks work! now just need build

**Comment by TheBunnyMan123** [comment]
Lmk when to merge

**Review by TheBunnyMan123 — APPROVED** [review]
Approved. Merge when ready

**Comment by PoolloverNathan** [comment]
ooh, 3 e's in a row! ~~collectible commit hashes when~~

**Pull request merged**
