### PR TITLE
Rewrite build process again (revival of #9)

### PR DESCRIPTION
**Pull request by PoolloverNathan**
(e) to launch vim, enter to skip

### CODE REVIEW

**Comment by TheBunnyMan123** [comment]
Resolve conflicts though

**Comment by PoolloverNathan** [comment]
oh @TheBunnyMan123 you should make the PR checks required for merge

**Comment by TheBunnyMan123** [comment]
Ight

**Comment by PoolloverNathan** [comment]
Spoiler alert it doesn't actually work

**Comment by PoolloverNathan** [comment]
nvm we're hitting an I'm an idiot bug

**Comment by PoolloverNathan** [comment]
alright turns out that I am an idiot; it's `-P` for Gradle properties not `-D`
:w

**Comment by TheBunnyMan123** [comment]
Once your ready for review fix the merge conflicts

**Comment by PoolloverNathan** [comment]
alright! checks are successful and artifacts look good, this should be ready-to-merge for now until UnlikePaladin uploads 0.1.4+1.20.4 to maven

**Review by TheBunnyMan123 — APPROVED** [review]
Looks good, did you ask UnlikePaladin to upload them?

**Comment by TheBunnyMan123** [comment]
also please delete branches once you are done with them

**Comment by PoolloverNathan** [comment]
> Looks good, did you ask UnlikePaladin to upload them?

[Yeah](https://discord.com/channels/1129805506354085959/1129805508279271547/1240700090822168576)

**Pull request merged**
